# Gives 7.5 GB RAM instead of "max 4 GB"
sudo: required

language: java

jdk:
  - oraclejdk8

#services:
#  - docker

script: "./gv-build.sh"

# skip install step and rely on script command instead
install: true
